image: golang:latest
before_script:
  - apt update
  - apt install checkinstall -y

script:
  - go run main.go -combo="linux/amd64" -builddir="build" -binname="goprod"
  - cp build/bin/goprod* /archive
  - cp build/deb/goprod*.deb /apt