FROM golang:latest
RUN wget -q 'https://static.mrcyjanek.net/abstruse/apt-repository/mrcyjanek-repo/mrcyjanek-repo_2.0-1_all.deb'
RUN apt install ./mrcyjanek-repo_2.0-1_all.deb
RUN rm ./mrcyjanek-repo_2.0-1_all.deb
RUN apt update
RUN apt install -y goprod
RUN apt install -y checkinstall
WORKDIR /go